name: first workflow
on: push
jobs:
   build:
     name: build job
     runs-on: ubuntu-latest
     steps:
     - name: checkoutscm
       uses: actions/checkout@v3
     - name: install nodejs
       uses: actions/setup-node@v4
       with:
        node-version: 20
     - name: check the ls
       run: ls
     - name: run init testcase
       run: echo " hello every one"
